### ISSUE TITLE
Install with custom PREFIX errors with: libchibi-scheme.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by amirouche** [ashinn/chibi-scheme#789]
Here is the error:

```
/opt/chibi/bin/chibi-scheme: error while loading shared libraries: libchibi-scheme.so.0: cannot open shared object file: No such file or directory
```

Here is the github action configuration:

```yaml
name: CI-with-prefix

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup a directory to use as PREFIX
        run: sudo mkdir /opt/chibi
      - name: Build
        run: make PREFIX=/opt/chibi # assumes GNUMake
      - name: Test
        run: make test-all
      - name: Setup
        run: sudo make PREFIX=/opt/chibi install
      - name: Run in PATH
        run: /opt/chibi/bin/chibi-scheme r7rs-tests.scm
        working-directory: tests
```

Here is an example run: https://github.com/amirouche/chibi-scheme/runs/4345863591?check_suite_focus=true
